---
title: "The Electric Guitar Threatens the Acoustic for Top Selling Spot"
subtitle: "An analysis of guitar sales data over 15 years and the trends between electric and acoustic."
author: "Liam Wall"
thanks: "Code and data are available at: https://github.com/Lwall02/guitars."
date: today
date-format: long
abstract: "Guitar sales in 2020 peaked at $1.3 billion a 60% increase from 2019 and the trend has continued to 2023 and has no signs of slowing in 2024. This paper delves into the sales of guitar sales in the United States over the past 15 years, employing a data on guitar sales by volumes, type of guitars, and their avergae price to understand the evolving preferences among consumers. The study of this data reveals  a significant shift in the popularity between electric and acoustic guitars, reflecting changing trends due to COVID-19 and economic, technological, and music preference changes. The findings not only chart the changing tastes of guitar enthusiasts and musicians but also hint at underlying factors driving these trends, offering valuable insights for manufacturers, retailers, and policymakers in the music industry."
format: pdf
number-sections: true
bibliography: references.bib
---

```{r}
#| include: false
#| warning: false
#| message: false

library(tidyverse)
library(palmerpenguins)
```


# Introduction

The guitar, an emblem of musical expression and cultural significance, has long been a staple in the global music industry. Its allure spans genres, from the soulful strains of acoustic melodies to the electrifying riffs of rock and roll. In the United States, the guitar market has experienced a remarkable resurgence in recent years, particularly highlighted by the significant spike in sales in 2020, where it peaked at $1.3 billion—a 60% increase from the previous year. This resurgence has not only continued through to 2023 but shows no signs of slowing as we move into 2024. The surge in guitar sales amidst the challenges of the COVID-19 pandemic and the changing economic landscape raises intriguing questions about the factors fueling this growth and the shifting preferences among guitar enthusiasts.

This research paper aims to explore the dynamics of guitar sales in the United States over the past 15 years, focusing on the sale volumes, types of guitars (electric and acoustic), and their average pricing. By analyzing these aspects, the study seeks to uncover the evolving consumer preferences that have contributed to the recent boom in guitar sales. The dataset utilized encompasses a broad range of sales data, offering a comprehensive overview of the market trends. This analysis is particularly relevant in the context of the COVID-19 pandemic, which has had a profound impact on consumer behavior and leisure activities, potentially influencing the spike in guitar sales. Moreover, the study considers how economic fluctuations, technological advancements, and shifts in musical preferences may have contributed to the changing landscape of guitar popularity.

The significant shift in the popularity between electric and acoustic guitars, as revealed by our study, reflects a broader narrative of change within the music industry and consumer habits. This paper not only charts these changing tastes among guitar enthusiasts and musicians but also delves into the underlying factors driving these trends. By doing so, it offers valuable insights for a wide range of stakeholders, including manufacturers, retailers, and policymakers in the music industry. Understanding these trends is crucial for adapting to the evolving market and for predicting future developments in the world of music and musical instruments. This research contributes to the broader discourse on cultural consumption patterns and the impact of global events on the arts and entertainment sectors, providing a window into the changing psyche of the modern consumer.

The open source programming language R was used in the making of this report (@citeR).

# Data {#sec-data}
## Annual Area Burnt By Wildfires
The data set downloaded from 'Our World in Data' contains the annual area burnt by wildfires per year from 2012 to 2024. The area burnt by wildfires in is reported in hectares. The data includes cumulative annual figures for Africa, Asia, Europe, North America, South America, and Oceania. The total figures for annual global data can be calculated by summing the mentioned regions. The data also contains complete 13 year data for 252 individual countries. 48 countries have recorded 0 hectares burnt for all 13 years of study @wildfire_data. This paper will cover the data from 2012 to 2022.

The area, in hectares, burnt by wildfires is estimated based the satellite imagery technologies MODIS (Moderate Resolution Imaging Spectroradiometer) and VIIRS (Visible Infrared Imaging Radiometer Suite). The VIIRS is a relatively new satellite first launched into orbit in late 2011. It collects data on the atmosphere, land, and oceans to measure a host of properties of Earth including present aerosols, ice movement, cloud properties, temperature data, and fires.  (@viirs). MODIS is another satellite that collects and montiors patterns on Earth's surface through satellite images. The information gathered is very useful for climatologists including global agricultural monitoring and forecasting, biogeo-chemical modeling, land use planning, land-cover change detection, and habitat preservation (@modis). 

The Global Wildfire Information System (GWIS) interprets the collected information from the above satellites and releases data sets which includes metrics such as the area of land burnt, cumulative burnt areas, carbon dioxide emissions from fires, cumulative carbon emissions, the number of fires, and cumulative fire counts. An important aspect to note and will be brought later in discussions is that GWIS is "presently engaged in a global accuracy assessment and acknowledged that they might be underestimating the genuine impact of wildfires, primarily due to constraints imposed by the spatial resolution of the sensors they employ" (@wildfire_data). This does not impede the effectivity of the data I employ as the underestimates still yield trends of interest. The data was made easily accessible through 'Our World in Data' with minor data cleaning. 

## Per Capita CO2 Emissions 
The data set downloaded from 'Our World in Data' contains annual per capita CO2 emissions per country or region, excluding land-use change, measured in tonnes per person. Land use change can release carbon dioxide into the air mainly through the process of agricultural conversion and will be covered in a separate data set. Similar to the wildfire data, it includes cumulative annual figures for Africa, Asia, Europe, North America, South America, Oceania, and the World (not included in wildfire data). As well as data for 252 countries spanning 1750 to 2022. I have selected only to examine the data from 2012 to 2022 for the cumulative figures mentioned above.For the purposes of this paper, we use the global data which is includes emissions from aviation and shipping. 

The Global Carbon Project (GCP) is an international science team that tracks the trends in global carbon emissions and sinks and is a key part of facilities the goals of the Paris Agreement. It's widely recognized as the most comprehensive report regarding carbon dioxide emissions. The GCP has been publishing estimates of global and national fossil CO2 emissions since 2001. (@gcp). The GCP has made their comprehensive data available and "Our World in Data' has cleaned and made it easily accessible. 

## Global Average Temperature 
The data set downloaded from "Our World in Data" contains detailed information on the average recorded temperature for 195 countries from 1940 to 2024. This data is produced by the Copernicus Climate Change Service which is ran by the European Centre for Medium-Range Weather Forecasts. The service provides hourly, global temperature data recorded all over the globe. There is both monthly and annual data, we focus on annual data in this paper. The temperature is recorded in Celcius and measured 2 meters above the surface of the land, sea, and in-land waters. The global average annual temperatures per year are obtained by averaging the 195 countries' data. (@temp_data).

## Global Population 
The data set downloaded from "Our World in Data' has made global population data released by the United Nations easily available (@pop_data). More specifically the Population Division of the Department of Economic and Social Affairs of the United Nations releases a revision of population data every two years. The 2022 Revision of World Population Prospects was released on 11 July, 2022 which contains estimates from 1950 to the present for 237 countries. The next revision of this data by the UN is due in 2024. The 2022 World Population Prospects considers the results of 1,758 national population censuses conducted between 1950 and 2022, as well as information from vital registration systems and from 2,890 nationally representative sample surveys. The 2022 revision also presents population projections to the year 2100 that reflect a range of plausible outcomes at the global, regional and national levels (@un_population).

## Sea Level
The data for the global mean sea level is produced by NASA using satellite radar altimetry. That is the process of measuring the distance of the surface from orbit using radar pulses. NASA make available the recorded change in sea level since January 5, 1993 to present. 




# Model

## Model set-up

### Model justification

# Results

# Discussion

## First discussion point {#sec-first-point}

## Second discussion point

## Third discussion point

## Weaknesses and next steps


\newpage

\appendix

# Appendix {-}

# Additional data details

# Model details {#sec-model-details}

## Posterior predictive check

## Diagnostics

\newpage


# References


